# RRN: Copied from template here: https://github.com/hvr/multi-ghc-travis/blob/master/README.md#ghc-head-snapshots

# NB: don't set `language: haskell` here

sudo: false
cache:
  directories:
  - $HOME/.stack/

matrix:
  include:
    - env: CABALVER=1.16 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3,happy,alex], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.3
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.3,happy-1.19.4,alex-3.1.3], sources: [hvr-ghc]}}
    # - env: CABALVER=1.18 GHCVER=7.8.4
    #   addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.4,alex-3.1.3], sources: [hvr-ghc]}}
    # - env: CABALVER=1.22 GHCVER=7.10.1
    #   addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}
# Huh, not approved yet [2015.08.23]:
#    - env: CABALVER=1.22 GHCVER=7.10.2
#      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2],sources: [hvr-ghc]}}

    - env: STACKVER=0.1.3.1 STACK_RESOLVER=lts-2.22
      addons: {apt: {packages: [ghc-7.8.4,happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}
    - env: STACKVER=0.1.3.1 STACK_RESOLVER=lts-3.2
      addons: {apt: {packages: [ghc-7.10.1,happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}

    - env: STACKVER=0.1.3.1 STACK_RESOLVER=ghc-7.8
      addons: {apt: {packages: [ghc-7.8.4,happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}
    - env: STACKVER=0.1.3.1 STACK_RESOLVER=ghc-7.10
      addons: {apt: {packages: [ghc-7.10.1,happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}

    - env: STACKVER=0.1.3.1 STACK_RESOLVER=nightly-2015-08-21
      addons: {apt: {packages: [happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}
    - env: STACKVER=0.1.3.1 STACK_RESOLVER=nightly
      addons: {apt: {packages: [happy-1.19.4,alex-3.1.3],sources: [hvr-ghc]}}

    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head
    # Too many headaches maintaining this for old cabal/ghc:
    - env: CABALVER=1.16 GHCVER=7.6.3
    # We test but don't guarantee the very latest nightly snapshot:
    - env: STACKVER=0.1.3.1 STACK_RESOLVER=nightly

# This is stack-specific.  Oh well.
before_install:
 - mkdir -p ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - cat /proc/cpuinfo | grep name
 - export STACK_YAML=stack-${STACK_RESOLVER}.yaml

install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - ./.travis_install.sh

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - ./.travis_script.sh
